# Generated by Django 2.2.4 on 2021-06-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professor',
            table=None,
        ),
    ]
